Fix file extension
vapor/core pull request #198
Opened 2019-03-27 16:06 UTC by timbaev

Return `nil` if file doesn't have extension

2019-03-27 16:49 UTC, calebkleveter approved these changes

2019-04-02 19:24 UTC, tanner0101 requested changes
LGTM overall, just one small typo. 

We should also make sure to fix this here, for Vapor 4:
https://github.com/vapor/http/blob/master/Sources/HTTPKit/Utilities/File.swift#L16

2019-04-02 19:24 UTC, tanner0101 commented on Sources/Core/File.swift
> +        let splitted = filename.split(separator: ".")
"to split" is irregular and is still "split" in the past tense. Another name for this could be `parts`.

2019-04-10 18:35 UTC, tanner0101 approved these changes
Thanks!

2019-04-10 18:40 UTC, merged

2019-04-10 18:40 UTC, penny-coin commented
Hey @timbaev, you just merged a pull request, have a coin! 

You now have 1 coins.